"""add_grocery_items_table

Revision ID: acbea2cfd78c
Revises: b7c1d4e9f2a3
Create Date: 2026-08-05 10:58:03.873044

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'acbea2cfd78c'
down_revision: Union[str, Sequence[str], None] = 'b7c1d4e9f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('added_by_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('purchased_by_id', sa.UUID(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchased_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_items_household_id'), 'grocery_items', ['household_id'], unique=False)
    # NOTE: autogenerate suggested dropping ix_users_email_lower (functional
    # index on lower(email)) — false positive; it exists in the DB and is
    # managed by the normalize_email_case migration. Left untouched.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grocery_items_household_id'), table_name='grocery_items')
    op.drop_table('grocery_items')
    # ### end Alembic commands ###
