"""full_schema

Revision ID: e3fadfdb700e
Revises: dffbcc647556
Create Date: 2026-06-25 15:22:54.630284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3fadfdb700e'
down_revision: Union[str, Sequence[str], None] = 'dffbcc647556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rotation_pointer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chore_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('kitchen', 'bathroom', 'bedroom', 'living_room', 'laundry_room', 'garden_outdoor', 'garage', 'other_general', name='chore_category'), nullable=False),
    sa.Column('effort_level', sa.Enum('easy', 'medium', 'hard', name='effort_level'), nullable=False),
    sa.Column('chore_type', sa.Enum('one_off', 'recurring', name='chore_type'), nullable=False),
    sa.Column('recurrence_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_due_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chore_definitions_household_id'), 'chore_definitions', ['household_id'], unique=False)
    op.create_table('household_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='membership_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_membership', 'household_memberships', ['household_id', 'user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('invite_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_tokens_token'), 'invite_tokens', ['token'], unique=True)
    op.create_table('chore_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=True),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('assigned_manually', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'complete', 'overdue', 'cancelled', name='chore_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['definition_id'], ['chore_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'due_date', name='uq_chore_instance_definition_due_date')
    )
    op.create_index('ix_chore_instances_assignee', 'chore_instances', ['assignee_id'], unique=False)
    op.create_index('ix_chore_instances_household_status', 'chore_instances', ['household_id', 'status'], unique=False)
    op.create_table('point_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chore_instance_id', sa.UUID(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chore_instance_id'], ['chore_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_point_ledger_household_user_awarded', 'point_ledger', ['household_id', 'user_id', 'awarded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_point_ledger_household_user_awarded', table_name='point_ledger')
    op.drop_table('point_ledger')
    op.drop_index('ix_chore_instances_household_status', table_name='chore_instances')
    op.drop_index('ix_chore_instances_assignee', table_name='chore_instances')
    op.drop_table('chore_instances')
    op.drop_index(op.f('ix_invite_tokens_token'), table_name='invite_tokens')
    op.drop_table('invite_tokens')
    op.drop_index('uq_active_membership', table_name='household_memberships', postgresql_where=sa.text('is_active = true'))
    op.drop_table('household_memberships')
    op.drop_index(op.f('ix_chore_definitions_household_id'), table_name='chore_definitions')
    op.drop_table('chore_definitions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('households')
    # Drop native PostgreSQL enum types
    sa.Enum(name='chore_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='chore_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='effort_level').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='chore_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='membership_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
